[package]
name = "fuzzy-phrase"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]

[dependencies]
fst = "0.3.0"
memmap = "0.6.2"
itertools = "0.7.8"
serde = "1.0.37"
rmp-serde = "0.13.7"
serde_derive = "1.0.37"

[dev-dependencies]
reqwest = "0.8.5"
byteorder = "1.2.2"

[dependencies.memmap]
version = "0.6.0"
optional = true

[dev-dependencies]
reqwest = "0.8.5"

[features]
default = ["mmap"]
mmap = ["memmap"]
