[package]
name = "fuzzy-phrase"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]

[dependencies]
fst = "0.3.0"
byteorder = "1.2.2"

[dependencies.memmap]
version = "0.6.0"
optional = true

[dev-dependencies]
reqwest = "0.8.5"

[features]
default = ["mmap"]
mmap = ["memmap"]
