version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/rust:1.31.1-jessie
    steps:
      - setup-docker-engine
      - checkout
      - run:
          name: Symlink Cargo
          command: ln -s /usr/local/cargo ~/.cargo
      - restore_cache:
          key: build-1.31.1jessie-{{ .Branch }}-{{ checksum "Cargo.toml" }}
      - run:
          name: Build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build
      - run:
          name: Test
          command: cargo test -- --nocapture
      - save_cache:
          key: build-1.31.1jessie-{{ .Branch }}-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo"
            - "./target"
      - run:
          name: Coverage
          command: |
            curl -sL https://github.com/xd009642/tarpaulin/releases/download/0.5.6/cargo-tarpaulin-0.5.6-travis.tar.gz | tar xvz -C $HOME/.cargo/bin
            cargo tarpaulin \
              --ciserver circle-ci \
              --verbose --out Xml
            bash <(curl -s https://codecov.io/bash)
